### ISSUE TITLE
SignUp Publishing

### ISSUE THREAD

**Issue by sookyoungwoo** [Intuition-Softech-Australia-Internship/Intution-Client#2]
### Describe

SignUp Page Publishing

### ✅ Tasks

- [x] Connect the login page
- [x] Implement various input fields
- [x] Creating a button using a button component
