### ISSUE TITLE
API 연결

### ISSUE THREAD

**Issue by sookyoungwoo** [Intuition-Softech-Australia-Internship/Intution-Client#4]
### Describe

Connect the API to enable the functionality of login and sign-up.

### ✅ Tasks

- [ ] Establish a connection to the server
- [ ] Communicate using Axios
- [ ] Display user information on the console upon successful login
